export const CATEGORIES = {
    "直播": "#bili_live",
    "推广": "#reportFirst2",
    "舞蹈": "#bili_dance",
    "时尚": "#bili_fashion",
    "知识": "#bili_technology",
    "生活": "#bili_life",
    "推荐": "#bili_report_spe_rec",
    "电视剧": "#bili_teleplay",
    "记录片": "#bili_documentary",
    "专栏": "#bili_read",
    "资讯": "#bili_information",
    "鬼畜": "#bili_kichiku",
    "娱乐": "#bili_ent",
    "游戏": "#bili_game",
    "影视": "#bili_cinephile",
    "国创": "#bili_guochuang",
    "漫画": "#bili_manga",
    "数码": "#bili_digital",
    "电影": "#bili_movie",
    "音乐": "#bili_music",
    "动画": "#bili_douga",
    "番剧": "#bili_anime",
    "侧边栏": "#elevator",
}
